#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl

write_files:
  - path: /root/install_coolify.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      export ROOT_USERNAME="${ROOT_USERNAME}"
      export ROOT_USER_EMAIL="${ROOT_USER_EMAIL}"
      export ROOT_USER_PASSWORD="${ROOT_USER_PASSWORD}"
      curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash

runcmd:
  - chmod +x /root/install_coolify.sh
  - /root/install_coolify.sh